package com.highqsoft.avalonCorbaNotification.notification;


/**
* com/highqsoft/avalonCorbaNotification/notification/AvalonNotificationCorbaEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/AvalonEvent.idl
* Freitag, 5. August 2016 09:43 Uhr MESZ
*/

public final class AvalonNotificationCorbaEvent implements org.omg.CORBA.portable.IDLEntity
{

  /**
  * The mode of the event.
  */
  public short mode = (short)0;

  /**
  * The Id of the application element.
  */
  public org.asam.ods.T_LONGLONG aeId = null;

  /**
  * The Id of the instance.
  */
  public org.asam.ods.T_LONGLONG ieId = null;

  /**
  * The Id of the AoUser instance.
  */
  public org.asam.ods.T_LONGLONG userId = null;

  /**
  * The timestamp of the event.
  */
  public String timestamp = null;

  public AvalonNotificationCorbaEvent ()
  {
  } // ctor

  public AvalonNotificationCorbaEvent (short _mode, org.asam.ods.T_LONGLONG _aeId, org.asam.ods.T_LONGLONG _ieId, org.asam.ods.T_LONGLONG _userId, String _timestamp)
  {
    mode = _mode;
    aeId = _aeId;
    ieId = _ieId;
    userId = _userId;
    timestamp = _timestamp;
  } // ctor

} // class AvalonNotificationCorbaEvent
