package com.highqsoft.avalonCorbaNotification.notification;


/**
* com/highqsoft/avalonCorbaNotification/notification/AvalonNotificationCorbaEventHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/AvalonEvent.idl
* Freitag, 5. August 2016 09:43 Uhr MESZ
*/

abstract public class AvalonNotificationCorbaEventHelper
{
  private static String  _id = "IDL:com/highqsoft/avalonCorbaNotification/notification/AvalonNotificationCorbaEvent:1.0";

  public static void insert (org.omg.CORBA.Any a, com.highqsoft.avalonCorbaNotification.notification.AvalonNotificationCorbaEvent that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.highqsoft.avalonCorbaNotification.notification.AvalonNotificationCorbaEvent extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[0] = new org.omg.CORBA.StructMember (
            "mode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.asam.ods.T_LONGLONGHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "aeId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.asam.ods.T_LONGLONGHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "ieId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.asam.ods.T_LONGLONGHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "userId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "timestamp",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.highqsoft.avalonCorbaNotification.notification.AvalonNotificationCorbaEventHelper.id (), "AvalonNotificationCorbaEvent", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.highqsoft.avalonCorbaNotification.notification.AvalonNotificationCorbaEvent read (org.omg.CORBA.portable.InputStream istream)
  {
    com.highqsoft.avalonCorbaNotification.notification.AvalonNotificationCorbaEvent value = new com.highqsoft.avalonCorbaNotification.notification.AvalonNotificationCorbaEvent ();
    value.mode = istream.read_short ();
    value.aeId = org.asam.ods.T_LONGLONGHelper.read (istream);
    value.ieId = org.asam.ods.T_LONGLONGHelper.read (istream);
    value.userId = org.asam.ods.T_LONGLONGHelper.read (istream);
    value.timestamp = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.highqsoft.avalonCorbaNotification.notification.AvalonNotificationCorbaEvent value)
  {
    ostream.write_short (value.mode);
    org.asam.ods.T_LONGLONGHelper.write (ostream, value.aeId);
    org.asam.ods.T_LONGLONGHelper.write (ostream, value.ieId);
    org.asam.ods.T_LONGLONGHelper.write (ostream, value.userId);
    ostream.write_string (value.timestamp);
  }

}
