package com.highqsoft.avalonCorbaNotification.notification;


/**
* com/highqsoft/avalonCorbaNotification/notification/MODE_DELETE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/idl/AvalonEvent.idl
* Freitag, 5. August 2016 09:43 Uhr MESZ
*/

public interface MODE_DELETE
{

  /**
  * The value of the mode field in the event when a delete is registered.
  */
  public static final short value = (short)(3);
}
