package org.asam.ods;


/**
 * Generated from IDL interface "ApplicationAttribute".
 *
 * @author JacORB IDL compiler V 2.3.0, 17-Feb-2007
 * @version generated at 28.09.2015 13:19:28
 */

public interface ApplicationAttributeOperations
{
	/* constants */
	/* operations  */
	org.asam.ods.BaseAttribute getBaseAttribute() throws org.asam.ods.AoException;
	org.asam.ods.DataType getDataType() throws org.asam.ods.AoException;
	int getLength() throws org.asam.ods.AoException;
	java.lang.String getName() throws org.asam.ods.AoException;
	org.asam.ods.T_LONGLONG getUnit() throws org.asam.ods.AoException;
	boolean isObligatory() throws org.asam.ods.AoException;
	boolean isUnique() throws org.asam.ods.AoException;
	void setBaseAttribute(org.asam.ods.BaseAttribute baseAttr) throws org.asam.ods.AoException;
	void setDataType(org.asam.ods.DataType aaDataType) throws org.asam.ods.AoException;
	void setIsObligatory(boolean aaIsObligatory) throws org.asam.ods.AoException;
	void setIsUnique(boolean aaIsUnique) throws org.asam.ods.AoException;
	void setLength(int aaLength) throws org.asam.ods.AoException;
	void setName(java.lang.String aaName) throws org.asam.ods.AoException;
	void setUnit(org.asam.ods.T_LONGLONG aaUnit) throws org.asam.ods.AoException;
	void setRights(org.asam.ods.InstanceElement usergroup, int rights, org.asam.ods.RightsSet set) throws org.asam.ods.AoException;
	org.asam.ods.ACL[] getRights() throws org.asam.ods.AoException;
	org.asam.ods.ApplicationElement getApplicationElement() throws org.asam.ods.AoException;
	boolean isAutogenerated() throws org.asam.ods.AoException;
	void setIsAutogenerated(boolean isAutogenerated) throws org.asam.ods.AoException;
	org.asam.ods.EnumerationDefinition getEnumerationDefinition() throws org.asam.ods.AoException;
	void setEnumerationDefinition(org.asam.ods.EnumerationDefinition enumDef) throws org.asam.ods.AoException;
	boolean hasUnit() throws org.asam.ods.AoException;
	void withUnit(boolean withUnit) throws org.asam.ods.AoException;
	boolean hasValueFlag() throws org.asam.ods.AoException;
	void withValueFlag(boolean withValueFlag) throws org.asam.ods.AoException;
}
